name: TestOlle OWASP ZAP with github actions

on:
  push:
    branches:
      - test-olle
  

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          target: 'http://testphp.vulnweb.com/'
          fail_action: true  # Fail the workflow if vulnerabilities are found
